default: &default
  adapter: postgresql
  encoding: utf-8
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 2 } %>

development:
  <<: *default
  database: local
  schema_search_path: 'projeto_angula' 

test: &test
  <<: *default
  database: local
  schema_search_path: 'projeto_angula'

cucumber:
  <<: *test